name: neom_image_editor
description: Image Editor for Open Neom.
version: 1.2.0
homepage: https://github.com/Open-Neom/neom_image_editor
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Open-Neom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Open-Neom/neom_commons.git

  image_cropper: ^9.1.0
  crop_your_image: ^1.1.0
  pro_image_editor: 12.4.4
  image_background_remover: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
